<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <PackageId>CodeOfChaos.Extensions.FluentValidation</PackageId>
        <Description>A Library of extensions for FluentValidation</Description>
        <PackageTags>extensions linq EntityFrameworkCore</PackageTags>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation" />
    </ItemGroup>

</Project>
