// ---------------------------------------------------------------------------------------------------------------------
// Imports
// ---------------------------------------------------------------------------------------------------------------------
using CodeOfChaos.Extensions.DependencyInjection;
using CodeOfChaos.Extensions.DependencyInjection.Generators;
using CodeOfChaos.Testing;
using CodeOfChaos.Testing.TUnit;
using JetBrains.Annotations;
using Microsoft.CodeAnalysis;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.ObjectPool;
using System;
using System.Threading.Tasks;
using Assembly=System.Reflection.Assembly;

namespace Tests.CodeOfChaos.Extensions.DependencyInjection.Generators;
// ---------------------------------------------------------------------------------------------------------------------
// Code
// ---------------------------------------------------------------------------------------------------------------------
public class ServiceRegistrationGeneratorTests {
    private static Assembly[] ReferenceAssemblies { get; } = [
        typeof(object).Assembly,
        typeof(FactoryCreatedServiceAttribute<,>).Assembly,
        typeof(IFactoryService<>).Assembly,
        typeof(InjectableAttribute<>).Assembly,
        typeof(ValueTuple).Assembly,// For tuples
        typeof(Attribute).Assembly,
        typeof(Console).Assembly,
        typeof(ServiceLifetime).Assembly,
        typeof(PooledObjectPolicy<>).Assembly,
        typeof(DefaultObjectPoolProvider).Assembly,
        Assembly.Load("System.Runtime")
    ];

    [Test]
    [Arguments(FactoryCreatedServiceInput, FactoryCreatedServiceOutput)]
    [Arguments(InjectableServiceInput, InjectableServiceOutput)]
    public async Task TestText(string inputText, string expectedOutput) {
        // Arrange
        RoslynGeneratorRunner runner = await new RoslynCompilationRunner()
            .AddReferences(ReferenceAssemblies)
            .AddDocument("Test.cs", inputText)
            .GetGeneratorRunnerAsync();

        // Act
        GeneratorDriverRunResult runResult = runner.AddGenerator<ServiceRegistrationGenerator>();

        // Assert
        await Assert.That(runResult).HasSourceTextEqualTo(
            "ServiceRegistration.g.cs",
            expectedOutput,
            ignoreWhiteSpace: true,
            withTrimming: true
        );
    }

    [Test]
    [Arguments(PooledInjectableServiceInput, PooledInjectableServiceOutput, PooledInjectableServiceOutputPooledServices)]
    public async Task TestPooledInjectableServiceOutput(string inputText, string expectedOutput, string expectedOutputPooledServices) {
        // Arrange
        RoslynGeneratorRunner runner = await new RoslynCompilationRunner()
            .AddReferences(ReferenceAssemblies)
            .AddDocument("Test.cs", inputText)
            .GetGeneratorRunnerAsync();

        // Act
        GeneratorDriverRunResult runResult = runner.AddGenerator<ServiceRegistrationGenerator>();

        // Assert
        await Assert.That(runResult).HasSourceTextEqualTo(
            "ServiceRegistration.g.cs",
            expectedOutput,
            ignoreWhiteSpace: true,
            withTrimming: true
        );

        await Assert.That(runResult).HasSourceTextEqualTo(
            "AutoPooledServices.g.cs",
            expectedOutputPooledServices,
            ignoreWhiteSpace: true,
            withTrimming: true
        );
    }

    #region FactoryCreatedService Test
    [LanguageInjection("csharp")] private const string FactoryCreatedServiceInput = """
        using Microsoft.Extensions.DependencyInjection;
        namespace TestNamespace {
            [CodeOfChaos.Extensions.DependencyInjection.FactoryCreatedService<IExampleFactory, ICreatedService>(ServiceLifetime.Transient)]
            public class CreatedService : ICreatedService;
            public interface ICreatedService;
            
            [CodeOfChaos.Extensions.DependencyInjection.InjectableService<IExampleFactory>(ServiceLifetime.Singleton)]
            public class ExampleFactory :IExampleFactory {
                public ICreatedService Create() => new CreatedService();
            }
            
            public interface IExampleFactory : CodeOfChaos.Extensions.DependencyInjection.IFactoryService<ICreatedService>;
        }

        """;

    [LanguageInjection("csharp")] private const string FactoryCreatedServiceOutput = """
        // <auto-generated />
        using Microsoft.Extensions.DependencyInjection;
        namespace TestProject;

        public static class ServiceRegistration {
            public static IServiceCollection RegisterServicesFromTestProject(this IServiceCollection services) {
                services.AddSingleton<TestNamespace.IExampleFactory, TestNamespace.ExampleFactory>();
                services.AddTransient<TestNamespace.ICreatedService>(
                    (provider) => provider.GetRequiredService<TestNamespace.IExampleFactory>().Create()
                );
                return services;
            }
        }

        """;
    #endregion

    #region InjectableService Test
    [LanguageInjection("csharp")] private const string InjectableServiceInput = """
        using Microsoft.Extensions.DependencyInjection;
        namespace TestNamespace {
            [CodeOfChaos.Extensions.DependencyInjection.InjectableService<IExampleService>(ServiceLifetime.Singleton)]
            public class ExampleService : IExampleService;
            
            
            public interface IExampleService;
        }

        """;

    [LanguageInjection("csharp")] private const string InjectableServiceOutput = """
        // <auto-generated />
        using Microsoft.Extensions.DependencyInjection;
        namespace TestProject;

        public static class ServiceRegistration {
            public static IServiceCollection RegisterServicesFromTestProject(this IServiceCollection services) {
                services.AddSingleton<TestNamespace.IExampleService, TestNamespace.ExampleService>();
                return services;
            }
        }

        """;
    #endregion

    #region PooledInjectableService Test
    [LanguageInjection("csharp")] private const string PooledInjectableServiceInput = """
        namespace TestProject;

        [CodeOfChaos.Extensions.DependencyInjection.PooledInjectableService<IExamplePooled, ExamplePooled>]
        public class ExamplePooled : IExamplePooled {
            public bool Reset() => true;
        }

        public interface IExamplePooled : CodeOfChaos.Extensions.DependencyInjection.IManualPoolable;
        """;

    [LanguageInjection("csharp")] private const string PooledInjectableServiceOutput = """
        // <auto-generated />
        using Microsoft.Extensions.DependencyInjection;
        namespace TestProject;

        public static class ServiceRegistration {
            public static IServiceCollection RegisterServicesFromTestProject(this IServiceCollection services) {
                services.AddSingleton<TestProject.AutoPooledServices>();
                services.AddTransient<TestProject.IExamplePooled>(
                    (provider) => provider.GetRequiredService<TestProject.AutoPooledServices>().ExamplePooledPool.Get()
                );
                return services;
            }
        }

        """;

    [LanguageInjection("csharp")] private const string PooledInjectableServiceOutputPooledServices = """
        // <auto-generated />
        using Microsoft.Extensions.ObjectPool;
        namespace TestProject;

        public partial class AutoPooledServices {
            private static readonly DefaultObjectPoolProvider _objectPoolProvider = new();
        
            public ObjectPool<TestProject.ExamplePooled> ExamplePooledPool { get; } = _objectPoolProvider
                .Create(new CodeOfChaos.Extensions.DependencyInjection.PooledInjectableServiceObjectPolicy<TestProject.ExamplePooled>());
        }

        """;
    #endregion
}
