<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CodeOfChaos.Testing.TUnit"/>
        <PackageReference Include="Microsoft.CodeAnalysis.Analyzers"/>
        <PackageReference Include="Microsoft.CodeAnalysis.Common" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
        <PackageReference Include="TUnit" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\CodeOfChaos.Extensions.Analyzers\CodeOfChaos.Extensions.Analyzers.csproj"/>
    </ItemGroup>

</Project>
