// ---------------------------------------------------------------------------------------------------------------------
// Imports
// ---------------------------------------------------------------------------------------------------------------------
using CodeOfChaos.GeneratorTools;
using System;
using System.Collections.Immutable;
using System.Linq;

namespace CodeOfChaos.Extensions.DependencyInjection.Generators;

// ---------------------------------------------------------------------------------------------------------------------
// Code
// ---------------------------------------------------------------------------------------------------------------------
public static class InjectableWriter {
    public static string GetSource(ImmutableArray<InjectableData> data, string assemblyName) {
        var builder = new GeneratorStringBuilder();
        builder.AppendAutoGenerated();
        builder.AppendUsings("Microsoft.Extensions.DependencyInjection");
        builder.AppendNamespace($"{assemblyName}._CodeOfChaosGenerated");
        builder.AppendLine("internal partial class InjectableUtility {");
        
        builder.AppendLineIndented($"private const string DEBUG_{Guid.NewGuid():N} = \"\"\"");
        builder.AppendLineIndented(string.Join("\n", data.Select(s => s.ToString())));
        builder.AppendLineIndented("\"\"\";");
        
        builder.AppendLine("}");
        return builder.ToString();
    }
}
