// ---------------------------------------------------------------------------------------------------------------------
// Imports
// ---------------------------------------------------------------------------------------------------------------------
using CodeOfChaos.GeneratorTools;
using System.Collections.Immutable;

namespace CodeOfChaos.Extensions.DependencyInjection.Generators;
// ---------------------------------------------------------------------------------------------------------------------
// Code
// ---------------------------------------------------------------------------------------------------------------------
public static class InjectableWriter {
    public static string GetSource(ImmutableArray<InjectableData> data, string assemblyName, ServiceLifetime lifetime) {
        var builder = new GeneratorStringBuilder();
        builder.AppendAutoGenerated();
        builder.AppendUsings("Microsoft.Extensions.DependencyInjection");
        builder.AppendNamespace($"{assemblyName}._CodeOfChaosGenerated");
        builder.AppendLine("internal partial class InjectableUtility {");

        builder.Indent(WriteFunction, (data, lifetime));

        builder.AppendLine("}");
        return builder.ToString();
    }
    private static void WriteFunction(GeneratorStringBuilder builder, (ImmutableArray<InjectableData> data, ServiceLifetime lifetime) valueTuple) {
        (ImmutableArray<InjectableData> data, ServiceLifetime lifetime) = valueTuple;

        string functionName = lifetime switch {
            ServiceLifetime.Singleton => "RegisterSingleton",
            ServiceLifetime.Scoped => "RegisterScoped",
            ServiceLifetime.Transient => "RegisterTransient",
            _ => "RegisterServices"
        };

        builder.AppendLine($"public static void {functionName}(IServiceCollection services) {{");

        builder.ForEachAppendLineIndented(data, ConvertInjectableDataToString);

        builder.AppendLine("}");
    }

    private static string ConvertInjectableDataToString(InjectableData arg) {
        // ReSharper disable once InvertIf
        if (arg.HasServiceKey) {
            string? key = arg.ServiceKeyIsString
                ? arg.ServiceKey.ToString().ToQuotedString()
                : arg.ServiceKey.ToString();
            return $"services.AddKeyed{arg.ServiceLifetime.ToFriendlyString()}<{arg.ServiceTypeName}, {arg.ClassName}>({key});";
        }

        return $"services.Add{arg.ServiceLifetime.ToFriendlyString()}<{arg.ServiceTypeName}, {arg.ClassName}>();";
    }
}
