// ---------------------------------------------------------------------------------------------------------------------
// Imports
// ---------------------------------------------------------------------------------------------------------------------
namespace CodeOfChaos.Extensions.DependencyInjection.Generators;

// ---------------------------------------------------------------------------------------------------------------------
// Code
// ---------------------------------------------------------------------------------------------------------------------
public static class SourceCodes {
    public const string InjectableAttributeTypeName = "CodeOfChaos.Extensions.DependencyInjection.InjectableAttribute`1";
    public const string InjectableSingletonAttributeTypeName = "CodeOfChaos.Extensions.DependencyInjection.InjectableSingletonAttribute`1";
    public const string InjectableScopedAttributeTypeName = "CodeOfChaos.Extensions.DependencyInjection.InjectableScopedAttribute`1";
    public const string InjectableTransientAttributeTypeName = "CodeOfChaos.Extensions.DependencyInjection.InjectableTransientAttribute`1";

    // -----------------------------------------------------------------------------------------------------------------
    // Methods
    // -----------------------------------------------------------------------------------------------------------------
    public static string GetInjectableGenerator(string assemblyName) => $$"""
    // <auto-generated />
    namespace {{assemblyName}};
    public static class CodeOfChaos_InjectableRegistration {
        public static IServiceCollection RegisterServicesFrom{{assemblyName.Replace(".", "")}}(IServiceCollection services){
            InjectableUtility.RegisterServices(services);
            InjectableUtility.RegisterSingleton(services);
            InjectableUtility.RegisterScoped(services);
            InjectableUtility.RegisterTransient(services);
            
            return services;   
        }
    }
    """;
}
