<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <PackageId>CodeOfChaos.Extensions.DependencyInjection</PackageId> <!-- Main package name -->
        <Description>A small package allowing easy collection of dependency injection services</Description>
        <PackageTags>dependency injection;di</PackageTags>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
        <PackageReference Include="Microsoft.Extensions.ObjectPool" />
    </ItemGroup>

</Project>
