<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <!-- Main package name -->
        <PackageId>CodeOfChaos.Extensions.AspNetCore.Components</PackageId>
        <Version>0.84.4</Version>
        <Authors>Anna Sas</Authors>
        <Description>A Library of broadly used extensions for AspNetCore Components</Description>
        <PackageProjectUrl>https://github.com/code-of-chaos/cs-code_of_chaos-extensions</PackageProjectUrl>
        <PackageTags>extensions AspNetCore</PackageTags>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <IncludeSymbols>true</IncludeSymbols>
        <DebugType>embedded</DebugType>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageIcon>icon.png</PackageIcon>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\..\LICENSE" Pack="true" PackagePath="" Visible="false" />
        <None Include="README.md" Pack="true" PackagePath="" />
        <None Include="../../assets/icon.png" Pack="true" PackagePath="" Visible="false" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Components" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CodeOfChaos.Extensions\CodeOfChaos.Extensions.csproj" />
    </ItemGroup>

</Project>
