<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <PackageId>CodeOfChaos.Extensions.Serilog</PackageId>
        <Description>A Library of broadly used extensions for Serilog</Description>
        <PackageTags>extensions Serilog</PackageTags>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CodeOfChaos.Ansi" />
        <PackageReference Include="JetBrains.Annotations" />
        <PackageReference Include="Serilog" />
        <PackageReference Include="Serilog.Sinks.Async" />
        <PackageReference Include="Serilog.Sinks.Console" />
    </ItemGroup>
</Project>
