<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>Microsoft.EntityFrameworkCore</RootNamespace>

        <!-- Main package name -->
        <PackageId>CodeOfChaos.Extensions.EntityFrameworkCore</PackageId>
        <Description>A Library of broadly used extensions for EntityFrameworkCore</Description>
        <PackageTags>extensions linq EntityFrameworkCore</PackageTags>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="CodeOfChaosTests.Extensions.EntityFrameworkCore" />
    </ItemGroup>
</Project>
