<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <PackageId>CodeOfChaos.Extensions</PackageId>
        <Description>A Library of broadly used extensions for dotnet in general</Description>
        <PackageTags>extensions linq collections string</PackageTags>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\CodeOfChaos.Extensions.Analyzers\CodeOfChaos.Extensions.Analyzers.csproj">
            <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
            <OutputItemType>Analyzer</OutputItemType>
            <IncludeAssets>compile; runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </ProjectReference>
    </ItemGroup>
</Project>
