<?xml version='1.0' encoding='utf-8'?>
<Project>
    <PropertyGroup>
        <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
        <LangVersion Condition="'$(TargetFramework)'=='net9.0'">13.0</LangVersion>
        <LangVersion Condition="'$(TargetFramework)'=='net10.0'">14.0</LangVersion>
        
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Deterministic>true</Deterministic>
        <DebugType>embedded</DebugType>
        <DebugSymbols>true</DebugSymbols>
        
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <RepositoryUrl>https://github.com/code-of-chaos/CodeOfChaos.Extensions.git</RepositoryUrl>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        
        <Version>0.92.0</Version>
        <Authors>Anna Sas</Authors>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageIcon>icon.png</PackageIcon>
        <PackageProjectUrl>https://github.com/code-of-chaos/CodeOfChaos.Extensions/</PackageProjectUrl>

        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    </PropertyGroup>
    
    <ItemGroup>
        <None Include="../../LICENSE" Pack="true" PackagePath="" Visible="false" />
        <None Include="../../README.md" Pack="true" PackagePath="" Visible="false" />
        <None Include="../../assets/icon.png" Pack="true" PackagePath="" Visible="false" />
    </ItemGroup>
</Project>