<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <DefineConstants>JETBRAINS_ANNOTATIONS</DefineConstants> <!-- Define JETBRAINS_ANNOTATIONS to ensure annotations are included -->

        <PackageId>CodeOfChaos.Extensions.MicrosoftLogging</PackageId>
        <Description>A simple extension library for Microsoft's logging</Description>
        <PackageTags>extensions linq EntityFrameworkCore</PackageTags>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    </ItemGroup>

</Project>
