name: "CI: Testing"

on:
    pull_request:
        types: [ opened, synchronize, reopened, ready_for_review ]
        branches: [ core ]
    workflow_dispatch:

jobs:
    tests-python:
        name: Python Testing
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v6

            -   name: Setup Python
                uses: actions/setup-python@v6
                with:
                    python-version: '3.x'

            -   name: Install Test Deps
                run: |
                    python -m pip install --upgrade pip
                    python -m pip install pytest

            -   name: Run Pytest
                run: python -m pytest .github/scripts -q

    test-dotnet:
        name: .NET Testing
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v6

            -   name: Setup .NET
                uses: actions/setup-dotnet@v5
                with:
                    dotnet-version: 10.x

            -   name: Restore dependencies
                run: dotnet restore CodeOfChaos.Markdown.Testing.slnf

            -   name: Build
                run: dotnet build CodeOfChaos.Markdown.Testing.slnf --configuration Release --no-restore

            -   name: Run tests
                run: dotnet test --solution CodeOfChaos.Markdown.Testing.slnf --configuration Release --no-restore --no-build
              